[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "nginx"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmds = [
  "nginx -c /app/nginx.conf -g 'daemon off;' & npm run start"
]